import { iBaseDTO, statusEnum } from "./base.types"

export interface iRestaurant extends iBaseDTO {
    id?: string,
    name: string,
    slug: string,
    logo?: string,
    description?: string,
    phone?: string,
    contactName?: string,
    contactPhone?: string,
    contactEmail?: string,
    notificationEmail?: string,
    address?: string,
    city?: string,
    postCode?: string,
    state?: string,
    country?: string,
    countryCode?: string,
    cuisines?: string[],
    serviceType?: string,
    status: statusEnum,
    subscription: string,
    subStartDate?: Date,
    subEndDate?: Date,
    facebookUrl?: string,
    instagramUrl?: string,
    tiktokUrl?: string,
    metaPixelId: number,
}